### ISSUE TITLE
image data redundancy and feeding to the GPU

### ISSUE THREAD

**Issue by thouis** [jegpeek/xorastro#2]
(discussion opener, rather than issue).

It might be worth moving viewpoint creation to the model.  TensorFlow has image rotation operations on the GPU (I think), and the viewpoints are slicing operations, so it could save some significant bandwidth during training, and simplify setup of training data.  It would also allow for some easy augmentation with a random angle applied to the (original, single) input image.

EDIT: I did the math, it would be useful for the 8 crops from the two 69x69 images, but not for any of the stages before that.

**Comment by jegpeek** [comment]
Very interesting; I don't know the TF or Keras gymnastics to do this, but I'd certainly prefer smaller data sets.

**Comment by exowanderer** [comment]
Yes, they do. 

If you want to expand the range of samples and include lots of corner cases, then TF suggests that we take the existing feature space and rotate, flip, rescale, etc the input images on the fly.  There is a `tf.image` sub-package that does randomized rotations, contrasts, and flips to increase the diversity of feature-space. 

It's actually considered a "regularization" technique, because it minimizes overfitting to the original features, stored on the hard drive.

![screen shot 2017-11-30 at 3 03 34 pm](https://user-images.githubusercontent.com/11221046/33452296-c1bd254e-d5df-11e7-9b3a-37c9d9007417.png)

**Comment by thouis** [comment]
NB: Most (all?) of those operate on single images, rather than batches, and use the CPU rather than the gpu, in most cases.

FWIW, I use some of them in this version of the network that takes full-res images as input and does all the "perspectives" construction in the network itself.  This is about 4x slower than the pre-computed version with 10K galaxies, but part of that is due to loading data from a larger training set:  https://github.com/thouis/xorastro/blob/ead503741efc7fdbddf23a22e6e99afec707cacf/galnet-250k.ipynb
